# Generated by Django 5.2.14 on 2026-05-26 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NEMO", "0148_unplannedoutage_resource_alter_unplannedoutage_tool"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                help_text="An optional invitee who is staff or authorized on the tool",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservation_invitee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
